version: '2.1'
services:

  ble-gateway:
    build:
      context: ./ble-gateway
    privileged: true
    restart: always
    network_mode: host

  metrics:
    build: ./metrics
    pid: host
    privileged: true
    network_mode: host
    restart: always
    labels:
      io.resin.features.balena-socket: '1'
      io.resin.features.dbus: '1'
