/** Declaration file generated by dts-gen */

export const FRAME_CONTROL: {
    BINDING_CFM: number;
    CAPABILITY_INCLUDE: number;
    CONNECTING: number;
    EVENT_INCLUDE: number;
    FACTORY_NEW: number;
    IS_CENTRAL: number;
    IS_ENCRYPTED: number;
    MAC_INCLUDE: number;
    MANU_DATA_INCLUDE: number;
    MANU_TITLE_INCLUDE: number;
};

export function readEventData(buffer: any, offset: any): any;

export function readServiceData(data: any): any;

export namespace EVENT_ID {
}

export namespace readEventData {
    const prototype: {
    };

}

export namespace readServiceData {
    const prototype: {
    };

}

